version: '3'

services:
  # Django application
  elib:
    container_name: elib
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9026:9026"
    volumes:
      - ./:/app/e_lib
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
#    command: bash -c "python manage.py migrate && python manage.py loaddata dictionary/fixtures/*.json && python manage.py runserver port=9025"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"

  # PostgreSQL database
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"