version: '3'

services:
  # Django application
  e_lib:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/app/e_lib
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    command: bash -c "python manage.py migrate && python manage.py loaddata dictionary/fixtures/*.json && python manage.py runserver 0.0.0.0:9000"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"

  # PostgreSQL database
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
