# Generated by Django 5.0.4 on 2024-04-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='related_synonyms', to='dictionary.word'),
        ),
    ]
