# Generated by Django 5.0.4 on 2024-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_partofspeech_word_parts_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(to='dictionary.word'),
        ),
    ]
