# Generated by Django 5.0.4 on 2024-05-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_translation_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='transcription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
